'use client';

import { useState } from 'react';
import { useApi } from '@/lib/hooks';
import { intelligenceApi } from '@/lib/api/intelligence';
import { PageHeader, Card, CardHeader, CardTitle, CardBody, Badge, Tabs } from '@/components/ui';
import { LoadingSpinner, ErrorState, EmptyState, confidenceColor, severityColor } from '@/lib/utils';

const TABS = [
  { key: 'predictions', label: 'Predictions' },
  { key: 'risks', label: 'Risk Assessments' },
  { key: 'anomalies', label: 'Anomalies' },
  { key: 'rootCauses', label: 'Root Causes' },
  { key: 'recommendations', label: 'Recommendations' },
];

function AIBadge() {
  return (
    <span className="inline-flex items-center gap-1 rounded-full bg-purple-50 border border-purple-200 px-2 py-0.5 text-xs font-medium text-purple-700">
      <svg className="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M12 2a4 4 0 0 0-4 4v2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8a2 2 0 0 0-2-2h-2V6a4 4 0 0 0-4-4z" />
        <circle cx="12" cy="15" r="2" />
      </svg>
      AI Generated
    </span>
  );
}

function Disclaimer() {
  return (
    <div className="rounded-md bg-amber-50 border border-amber-200 px-4 py-3 text-sm text-amber-800 flex items-start gap-2">
      <svg className="h-4 w-4 mt-0.5 flex-shrink-0" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 1 1-18 0 9 9 0 0 1 18 0zm-9 3.75h.008v.008H12v-.008z" />
      </svg>
      <div>
        <span className="font-semibold">AI-Generated Intelligence</span> — These results are predictions, risk assessments, and recommendations generated by AI models. They are analytical interpretations and should not be treated as authoritative facts. Always verify critical decisions with qualified personnel.
      </div>
    </div>
  );
}

function riskLevelColor(level: string) {
  switch (level) {
    case 'critical': return 'red' as const;
    case 'high': return 'red' as const;
    case 'medium': return 'yellow' as const;
    case 'low': return 'blue' as const;
    default: return 'gray' as const;
  }
}

function statusBadgeColor(status: string) {
  switch (status) {
    case 'active': return 'green' as const;
    case 'expired': return 'gray' as const;
    case 'superseded': return 'blue' as const;
    default: return 'gray' as const;
  }
}

function priorityBadgeColor(priority: string) {
  switch (priority) {
    case 'CRITICAL': return 'red' as const;
    case 'HIGH': return 'red' as const;
    case 'MEDIUM': return 'yellow' as const;
    case 'LOW': return 'blue' as const;
    default: return 'gray' as const;
  }
}

function severityBadgeColor(severity: string) {
  switch (severity) {
    case 'critical': return 'red' as const;
    case 'high': return 'red' as const;
    case 'medium': return 'yellow' as const;
    case 'low': return 'blue' as const;
    default: return 'gray' as const;
  }
}

function PredictionsTab() {
  const { data, loading, error, refetch } = useApi(() => intelligenceApi.getPredictions(), []);

  if (loading) return <LoadingSpinner />;
  if (error) return <ErrorState message={error} onRetry={refetch} />;
  if (!data || data.length === 0) return <EmptyState title="No predictions" description="No AI predictions are currently available." />;

  return (
    <div className="space-y-4">
      {data.map((p) => (
        <Card key={p.id}>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>{p.predictionType}</CardTitle>
              <div className="flex items-center gap-2">
                <AIBadge />
                <Badge variant={statusBadgeColor(p.status)}>{p.status}</Badge>
              </div>
            </div>
          </CardHeader>
          <CardBody className="space-y-3">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
              <div>
                <p className="text-gray-500">Probability</p>
                <p className="text-lg font-semibold">{(p.probability * 100).toFixed(1)}%</p>
              </div>
              <div>
                <p className="text-gray-500">Confidence</p>
                <p className={`font-medium ${confidenceColor(p.confidence)}`}>{p.confidence}</p>
              </div>
              <div>
                <p className="text-gray-500">Horizon</p>
                <p className="font-medium">{p.horizon}h</p>
              </div>
              <div>
                <p className="text-gray-500">Model</p>
                <p className="font-medium font-mono text-xs">{p.model}</p>
              </div>
            </div>
            {p.explanation && (
              <p className="text-sm text-gray-700">{p.explanation}</p>
            )}
            {p.evidence.length > 0 && (
              <div>
                <p className="text-xs font-medium text-gray-500 mb-1">Evidence Sources</p>
                <div className="flex flex-wrap gap-2">
                  {p.evidence.map((e, i) => (
                    <span key={i} className="text-xs bg-gray-100 rounded px-2 py-1 text-gray-600">
                      {e.sourceType}: {e.reason}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </CardBody>
        </Card>
      ))}
    </div>
  );
}

function RisksTab() {
  const { data, loading, error, refetch } = useApi(() => intelligenceApi.getRisks(), []);

  if (loading) return <LoadingSpinner />;
  if (error) return <ErrorState message={error} onRetry={refetch} />;
  if (!data || data.length === 0) return <EmptyState title="No risk assessments" description="No AI risk assessments are currently available." />;

  return (
    <div className="space-y-4">
      {data.map((r) => (
        <Card key={r.id}>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>{r.subjectType}: {r.subjectId}</CardTitle>
              <div className="flex items-center gap-2">
                <AIBadge />
                <Badge variant={riskLevelColor(r.riskLevel)}>{r.riskLevel}</Badge>
              </div>
            </div>
          </CardHeader>
          <CardBody className="space-y-3">
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4 text-sm">
              <div>
                <p className="text-gray-500">Risk Level</p>
                <p className={`font-semibold uppercase text-sm ${riskLevelColor(r.riskLevel) === 'red' ? 'text-red-600' : riskLevelColor(r.riskLevel) === 'yellow' ? 'text-yellow-600' : 'text-blue-600'}`}>{r.riskLevel}</p>
              </div>
              <div>
                <p className="text-gray-500">Confidence</p>
                <p className={`font-medium ${confidenceColor(r.confidence)}`}>{r.confidence}</p>
              </div>
              <div>
                <p className="text-gray-500">Status</p>
                <p className="font-medium">{r.status}</p>
              </div>
            </div>
            {r.factors.length > 0 && (
              <div>
                <p className="text-xs font-medium text-gray-500 mb-2">Risk Factors</p>
                <ul className="divide-y border rounded-md">
                  {r.factors.map((f, i) => (
                    <li key={i} className="px-3 py-2 text-sm">
                      <div className="flex items-center justify-between">
                        <span className="font-medium">{f.name}</span>
                        <span className="text-xs text-gray-500">weight: {(f.weight * 100).toFixed(0)}%</span>
                      </div>
                      <p className="text-gray-600 text-xs mt-0.5">{f.description}</p>
                    </li>
                  ))}
                </ul>
              </div>
            )}
            {r.explanation && (
              <p className="text-sm text-gray-700">{r.explanation}</p>
            )}
          </CardBody>
        </Card>
      ))}
    </div>
  );
}

function AnomaliesTab() {
  const { data, loading, error, refetch } = useApi(() => intelligenceApi.getAnomalies(), []);

  if (loading) return <LoadingSpinner />;
  if (error) return <ErrorState message={error} onRetry={refetch} />;
  if (!data || data.length === 0) return <EmptyState title="No anomalies" description="No AI-detected anomalies are currently available." />;

  return (
    <div className="space-y-4">
      {data.map((a) => (
        <Card key={a.id}>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>{a.anomalyType}</CardTitle>
              <div className="flex items-center gap-2">
                <AIBadge />
                <Badge variant={severityBadgeColor(a.severity)}>{a.severity}</Badge>
              </div>
            </div>
          </CardHeader>
          <CardBody className="space-y-3">
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4 text-sm">
              <div>
                <p className="text-gray-500">Severity</p>
                <Badge variant={severityBadgeColor(a.severity)}>{a.severity}</Badge>
              </div>
              <div>
                <p className="text-gray-500">Anomaly Score</p>
                <p className="font-semibold">{(a.score * 100).toFixed(1)}%</p>
              </div>
              <div>
                <p className="text-gray-500">Confidence</p>
                <p className={`font-medium ${confidenceColor(a.confidence)}`}>{a.confidence}</p>
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
              <div className="rounded-md bg-blue-50 border border-blue-100 p-3">
                <p className="text-xs font-medium text-blue-700 mb-1">Expected Behavior</p>
                <p className="text-sm text-blue-800">{a.expectedBehavior}</p>
              </div>
              <div className="rounded-md bg-orange-50 border border-orange-100 p-3">
                <p className="text-xs font-medium text-orange-700 mb-1">Observed Behavior</p>
                <p className="text-sm text-orange-800">{a.observedBehavior}</p>
              </div>
            </div>
            {a.explanation && (
              <p className="text-sm text-gray-700">{a.explanation}</p>
            )}
            {a.evidence.length > 0 && (
              <div>
                <p className="text-xs font-medium text-gray-500 mb-1">Evidence Sources</p>
                <div className="flex flex-wrap gap-2">
                  {a.evidence.map((e, i) => (
                    <span key={i} className="text-xs bg-gray-100 rounded px-2 py-1 text-gray-600">
                      {e.sourceType}: {e.reason}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </CardBody>
        </Card>
      ))}
    </div>
  );
}

function RootCausesTab() {
  const { data, loading, error, refetch } = useApi(() => intelligenceApi.getRootCauses(), []);

  if (loading) return <LoadingSpinner />;
  if (error) return <ErrorState message={error} onRetry={refetch} />;
  if (!data || data.length === 0) return <EmptyState title="No root causes" description="No AI root cause analyses are currently available." />;

  return (
    <div className="space-y-4">
      {data.map((rc) => (
        <Card key={rc.id}>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>Root Cause: {rc.subjectType}: {rc.subjectId}</CardTitle>
              <AIBadge />
            </div>
          </CardHeader>
          <CardBody className="space-y-3">
            {rc.explanation && (
              <p className="text-sm text-gray-700">{rc.explanation}</p>
            )}
            {rc.candidates.length > 0 && (
              <div>
                <p className="text-xs font-medium text-gray-500 mb-2">Candidate Causes</p>
                <div className="divide-y border rounded-md">
                  {rc.candidates.map((c, i) => (
                    <div key={i} className="px-3 py-2 text-sm">
                      <div className="flex items-center justify-between">
                        <span className="font-medium">{c.cause}</span>
                        <span className={`text-xs font-medium ${confidenceColor(c.confidence)}`}>{c.confidence}</span>
                      </div>
                      {c.description && (
                        <p className="text-gray-600 text-xs mt-1">{c.description}</p>
                      )}
                      {c.evidence.length > 0 && (
                        <div className="flex flex-wrap gap-1 mt-1">
                          {c.evidence.map((e, j) => (
                            <span key={j} className="text-xs bg-gray-50 rounded px-1.5 py-0.5 text-gray-500">
                              {e.sourceType}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </CardBody>
        </Card>
      ))}
    </div>
  );
}

function RecommendationsTab() {
  const { data, loading, error, refetch } = useApi(() => intelligenceApi.getRecommendations(), []);

  if (loading) return <LoadingSpinner />;
  if (error) return <ErrorState message={error} onRetry={refetch} />;
  if (!data || data.length === 0) return <EmptyState title="No recommendations" description="No AI recommendations are currently available." />;

  return (
    <div className="space-y-4">
      {data.map((r) => (
        <Card key={r.id}>
          <CardHeader>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <CardTitle>{r.recommendation}</CardTitle>
                {r.requiredApproval && (
                  <Badge variant="yellow">Approval Required: {r.requiredApproval}</Badge>
                )}
              </div>
              <div className="flex items-center gap-2">
                <AIBadge />
                <Badge variant={priorityBadgeColor(r.priority)}>{r.priority}</Badge>
              </div>
            </div>
          </CardHeader>
          <CardBody className="space-y-3">
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4 text-sm">
              <div>
                <p className="text-gray-500">Priority</p>
                <Badge variant={priorityBadgeColor(r.priority)}>{r.priority}</Badge>
              </div>
              <div>
                <p className="text-gray-500">Confidence</p>
                <p className={`font-medium ${confidenceColor(r.confidence)}`}>{r.confidence}</p>
              </div>
              <div>
                <p className="text-gray-500">Impact</p>
                <p className="font-medium">{r.impact}</p>
              </div>
            </div>
            {r.evidence.length > 0 && (
              <div>
                <p className="text-xs font-medium text-gray-500 mb-1">Evidence Sources</p>
                <div className="flex flex-wrap gap-2">
                  {r.evidence.map((e, i) => (
                    <span key={i} className="text-xs bg-gray-100 rounded px-2 py-1 text-gray-600">
                      {e.sourceType}: {e.reason}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </CardBody>
        </Card>
      ))}
    </div>
  );
}

export default function IntelligencePage() {
  const [activeTab, setActiveTab] = useState('predictions');

  return (
    <div className="space-y-6">
      <PageHeader
        breadcrumbs={[{ label: 'Intelligence', href: '/intelligence' }, { label: 'Overview' }]}
        title="AI Intelligence Center"
        subtitle="Layer 8 AI Predictions, Risk Analysis, Anomaly Detection & Root Causes"
      />

      <Disclaimer />

      <Tabs tabs={TABS} active={activeTab} onChange={setActiveTab} />

      {activeTab === 'predictions' && <PredictionsTab />}
      {activeTab === 'risks' && <RisksTab />}
      {activeTab === 'anomalies' && <AnomaliesTab />}
      {activeTab === 'rootCauses' && <RootCausesTab />}
      {activeTab === 'recommendations' && <RecommendationsTab />}
    </div>
  );
}
