import { pgTable, varchar, text, timestamp, uuid, integer } from 'drizzle-orm/pg-core';

export const cases = pgTable('cases', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull(),
  caseNumber: varchar('case_number', { length: 50 }).notNull(),
  caseType: varchar('case_type', { length: 50 }).notNull(),
  baggageId: uuid('baggage_id'),
  flightId: uuid('flight_id'),
  journeyId: uuid('journey_id'),
  title: varchar('title', { length: 255 }),
  priority: varchar('priority', { length: 20 }).notNull().default('medium'),
  status: varchar('status', { length: 30 }).notNull().default('open'),
  assignedTo: uuid('assigned_to'),
  assignedOrganizationId: uuid('assigned_organization_id'),
  originOrganizationId: uuid('origin_organization_id'),
  sourceExceptionId: uuid('source_exception_id'),
  source: varchar('source', { length: 50 }).notNull().default('operator'),
  description: text('description'),
  resolution: text('resolution'),
  resolutionCode: varchar('resolution_code', { length: 50 }),
  resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  closedAt: timestamp('closed_at', { withTimezone: true }),
  escalatedAt: timestamp('escalated_at', { withTimezone: true }),
  workflowId: uuid('workflow_id'),
  metadata: text('metadata'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
